//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BalitTanahPelayanan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class accounttbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public accounttbl()
        {
            this.customertbls = new HashSet<customertbl>();
            this.employeetbls = new HashSet<employeetbl>();
        }
    
        public int accountNo { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string roleName { get; set; }
        public string isEmailVerified { get; set; }
        public string creaBy { get; set; }
        public Nullable<System.DateTime> creaDate { get; set; }
        public string modBy { get; set; }
        public Nullable<System.DateTime> modDate { get; set; }
    
        public virtual roletbl roletbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<customertbl> customertbls { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<employeetbl> employeetbls { get; set; }
    }
}
