//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BalitTanahPelayanan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class batchtbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public batchtbl()
        {
            this.ordermastertbls = new HashSet<ordermastertbl>();
        }
    
        public string batchId { get; set; }
        public string filename { get; set; }
        public string status { get; set; }
        public string fileurl { get; set; }
        public Nullable<int> pic_analis { get; set; }
        public Nullable<int> pic_penyelia { get; set; }
        public string creaBy { get; set; }
        public Nullable<System.DateTime> creaDate { get; set; }
        public string modBy { get; set; }
        public Nullable<System.DateTime> modDate { get; set; }
    
        public virtual employeetbl employeetbl { get; set; }
        public virtual employeetbl employeetbl1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ordermastertbl> ordermastertbls { get; set; }
    }
}
