//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BalitTanahPelayanan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class comoditytbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public comoditytbl()
        {
            this.genustbls = new HashSet<genustbl>();
            this.ordermastertbls = new HashSet<ordermastertbl>();
            this.packagetbls = new HashSet<packagetbl>();
            this.standardtbls = new HashSet<standardtbl>();
        }
    
        public int comodityNo { get; set; }
        public string comodityName { get; set; }
        public Nullable<int> derivativeTo { get; set; }
        public string description { get; set; }
        public string code { get; set; }
        public string notes { get; set; }
        public string isPackage { get; set; }
        public string creaBy { get; set; }
        public Nullable<System.DateTime> creaDate { get; set; }
        public string modBy { get; set; }
        public Nullable<System.DateTime> modDate { get; set; }
        public string isGenusAvailable { get; set; }
        public Nullable<decimal> priceGenusPerSample { get; set; }
        public string isHeavyMetalAvailable { get; set; }
        public Nullable<decimal> limitDoseForFreeOfHeavyMetal { get; set; }
        public Nullable<decimal> priceHeavyMetalPerSample { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<genustbl> genustbls { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ordermastertbl> ordermastertbls { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<packagetbl> packagetbls { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<standardtbl> standardtbls { get; set; }
    }
}
