//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BalitTanahPelayanan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class elementservicestbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public elementservicestbl()
        {
            this.elementservicehistorytbls = new HashSet<elementservicehistorytbl>();
            this.orderanalysisdetailtbls = new HashSet<orderanalysisdetailtbl>();
            this.orderpricedetailtbls = new HashSet<orderpricedetailtbl>();
            this.packagedetailtbls = new HashSet<packagedetailtbl>();
            this.standarddetailtbls = new HashSet<standarddetailtbl>();
        }
    
        public int elementid { get; set; }
        public string elementCode { get; set; }
        public int comodityNo { get; set; }
        public string analysisTypeName { get; set; }
        public string valueUnit { get; set; }
        public string serviceGroup { get; set; }
        public decimal serviceRate { get; set; }
        public string serviceStatus { get; set; }
        public string category { get; set; }
        public Nullable<int> sortedNo { get; set; }
        public string isMandatory { get; set; }
        public string creaBy { get; set; }
        public Nullable<System.DateTime> creaDate { get; set; }
        public string modBy { get; set; }
        public Nullable<System.DateTime> modDate { get; set; }
        public string NotParameterProcess { get; set; }
        public string ExtractionId { get; set; }
    
        public virtual analysistypetbl analysistypetbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<elementservicehistorytbl> elementservicehistorytbls { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<orderanalysisdetailtbl> orderanalysisdetailtbls { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<orderpricedetailtbl> orderpricedetailtbls { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<packagedetailtbl> packagedetailtbls { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<standarddetailtbl> standarddetailtbls { get; set; }
    }
}
