//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BalitTanahPelayanan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class employeetbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public employeetbl()
        {
            this.batchtbls = new HashSet<batchtbl>();
            this.batchtbls1 = new HashSet<batchtbl>();
            this.orderanalysisdetailtbls = new HashSet<orderanalysisdetailtbl>();
            this.ordermastertbls = new HashSet<ordermastertbl>();
        }
    
        public int employeeNo { get; set; }
        public string employeeName { get; set; }
        public string position { get; set; }
        public string employeeEmail { get; set; }
        public Nullable<int> derivativeToEmployee { get; set; }
        public Nullable<int> accountNo { get; set; }
        public string creaBy { get; set; }
        public Nullable<System.DateTime> creaDate { get; set; }
        public string modBy { get; set; }
        public Nullable<System.DateTime> modDate { get; set; }
        public Nullable<int> laboratoriumID { get; set; }
    
        public virtual accounttbl accounttbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<batchtbl> batchtbls { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<batchtbl> batchtbls1 { get; set; }
        public virtual laboratoriumtbl laboratoriumtbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<orderanalysisdetailtbl> orderanalysisdetailtbls { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ordermastertbl> ordermastertbls { get; set; }
    }
}
