//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BalitTanahPelayanan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class my_aspnet_profiles
    {
        public int userId { get; set; }
        public string valueindex { get; set; }
        public string stringdata { get; set; }
        public byte[] binarydata { get; set; }
        public Nullable<System.DateTime> lastUpdatedDate { get; set; }
    }
}
