//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BalitTanahPelayanan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class orderanalysisdetailtbl
    {
        public int orderDetailNo { get; set; }
        public string orderNo { get; set; }
        public string sampleNo { get; set; }
        public int elementId { get; set; }
        public Nullable<int> parametersNo { get; set; }
        public string elementValue { get; set; }
        public string status { get; set; }
        public string recalculate { get; set; }
        public Nullable<int> pic { get; set; }
        public string fileAttachmentUrl { get; set; }
        public string fileName { get; set; }
        public string LabToolAttachmentUrl { get; set; }
        public string LabToolFileName { get; set; }
        public string creaBy { get; set; }
        public Nullable<System.DateTime> creaDate { get; set; }
        public string modBy { get; set; }
        public Nullable<System.DateTime> modDate { get; set; }
    
        public virtual elementservicestbl elementservicestbl { get; set; }
        public virtual employeetbl employeetbl { get; set; }
        public virtual ordermastertbl ordermastertbl { get; set; }
        public virtual ordersampletbl ordersampletbl { get; set; }
        public virtual parameterstbl parameterstbl { get; set; }
    }
}
