//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BalitTanahPelayanan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ordermastertbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ordermastertbl()
        {
            this.orderanalysisdetailtbls = new HashSet<orderanalysisdetailtbl>();
            this.orderpricedetailtbls = new HashSet<orderpricedetailtbl>();
            this.ordersampletbls = new HashSet<ordersampletbl>();
            this.resulttbls = new HashSet<resulttbl>();
        }
    
        public string orderNo { get; set; }
        public string batchId { get; set; }
        public int customerNo { get; set; }
        public int comodityNo { get; set; }
        public string analysisType { get; set; }
        public Nullable<int> sampleTotal { get; set; }
        public Nullable<decimal> priceTotal { get; set; }
        public string statusType { get; set; }
        public string status { get; set; }
        public string paymentStatus { get; set; }
        public Nullable<decimal> ppn { get; set; }
        public Nullable<System.DateTime> receiptDate { get; set; }
        public string isPaid { get; set; }
        public Nullable<System.DateTime> paymentDate { get; set; }
        public Nullable<int> pic { get; set; }
        public string isOnLab { get; set; }
        public string ApprPenyelia { get; set; }
        public string ApprEvaluator { get; set; }
        public string ApprManagerTeknis { get; set; }
        public string LHPAttachmentUrl { get; set; }
        public string LHPFileName { get; set; }
        public string EvaluationFileUrl { get; set; }
        public string EvaluationFileName { get; set; }
        public string isRecalculate { get; set; }
        public string CalculationFileUrl { get; set; }
        public string CalculationFilename { get; set; }
        public string isReviewing { get; set; }
        public string packageName { get; set; }
        public Nullable<decimal> additionalPrice1 { get; set; }
        public Nullable<decimal> additionalPrice2 { get; set; }
        public Nullable<int> totalGenus { get; set; }
        public Nullable<decimal> dosePerHectare { get; set; }
        public string additionalPriceRemark { get; set; }
        public string creaBy { get; set; }
        public Nullable<System.DateTime> creaDate { get; set; }
        public string modBy { get; set; }
        public Nullable<System.DateTime> modDate { get; set; }
    
        public virtual analysistypetbl analysistypetbl { get; set; }
        public virtual batchtbl batchtbl { get; set; }
        public virtual comoditytbl comoditytbl { get; set; }
        public virtual customertbl customertbl { get; set; }
        public virtual employeetbl employeetbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<orderanalysisdetailtbl> orderanalysisdetailtbls { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<orderpricedetailtbl> orderpricedetailtbls { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ordersampletbl> ordersampletbls { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<resulttbl> resulttbls { get; set; }
    }
}
