//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BalitTanahPelayanan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class orderpricedetailtbl
    {
        public int orderPriceDetailNo { get; set; }
        public string orderNo { get; set; }
        public Nullable<int> elementId { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
    
        public virtual elementservicestbl elementservicestbl { get; set; }
        public virtual ordermastertbl ordermastertbl { get; set; }
    }
}
