//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BalitTanahPelayanan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class packagetbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public packagetbl()
        {
            this.packagedetailtbls = new HashSet<packagedetailtbl>();
        }
    
        public string packageName { get; set; }
        public Nullable<int> comodityNo { get; set; }
        public string analysisTypeName { get; set; }
        public string multipleSelectedItem { get; set; }
        public Nullable<decimal> bundlePrice { get; set; }
        public Nullable<decimal> additionalPrice1 { get; set; }
        public Nullable<decimal> additionalPrice2 { get; set; }
        public string additionalPriceDesc1 { get; set; }
        public string additionalPriceDesc2 { get; set; }
    
        public virtual analysistypetbl analysistypetbl { get; set; }
        public virtual comoditytbl comoditytbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<packagedetailtbl> packagedetailtbls { get; set; }
    }
}
