//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BalitTanahPelayanan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class resulttbl
    {
        public int resultNo { get; set; }
        public string orderNo { get; set; }
        public Nullable<int> reviewingNo { get; set; }
        public string url { get; set; }
        public string fileName { get; set; }
        public string creaBy { get; set; }
        public Nullable<System.DateTime> creaDate { get; set; }
        public string modBy { get; set; }
        public Nullable<System.DateTime> modDate { get; set; }
    
        public virtual ordermastertbl ordermastertbl { get; set; }
        public virtual reviewingtbl reviewingtbl { get; set; }
    }
}
