//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BalitTanahPelayanan.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class smlpobDB : DbContext
    {
        public smlpobDB()
            : base("name=smlpobDB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<accounttbl> accounttbls { get; set; }
        public virtual DbSet<analysistypetbl> analysistypetbls { get; set; }
        public virtual DbSet<autonumbertbl> autonumbertbls { get; set; }
        public virtual DbSet<batchtbl> batchtbls { get; set; }
        public virtual DbSet<comoditytbl> comoditytbls { get; set; }
        public virtual DbSet<customertbl> customertbls { get; set; }
        public virtual DbSet<elementservicehistorytbl> elementservicehistorytbls { get; set; }
        public virtual DbSet<elementservicestbl> elementservicestbls { get; set; }
        public virtual DbSet<employeetbl> employeetbls { get; set; }
        public virtual DbSet<genustbl> genustbls { get; set; }
        public virtual DbSet<laboratoriumtbl> laboratoriumtbls { get; set; }
        public virtual DbSet<logtbl> logtbls { get; set; }
        public virtual DbSet<my_aspnet_applications> my_aspnet_applications { get; set; }
        public virtual DbSet<my_aspnet_membership> my_aspnet_membership { get; set; }
        public virtual DbSet<my_aspnet_paths> my_aspnet_paths { get; set; }
        public virtual DbSet<my_aspnet_personalizationallusers> my_aspnet_personalizationallusers { get; set; }
        public virtual DbSet<my_aspnet_personalizationperuser> my_aspnet_personalizationperuser { get; set; }
        public virtual DbSet<my_aspnet_profiles> my_aspnet_profiles { get; set; }
        public virtual DbSet<my_aspnet_roles> my_aspnet_roles { get; set; }
        public virtual DbSet<my_aspnet_sessioncleanup> my_aspnet_sessioncleanup { get; set; }
        public virtual DbSet<my_aspnet_sessions> my_aspnet_sessions { get; set; }
        public virtual DbSet<my_aspnet_sitemap> my_aspnet_sitemap { get; set; }
        public virtual DbSet<my_aspnet_users> my_aspnet_users { get; set; }
        public virtual DbSet<my_aspnet_usersinroles> my_aspnet_usersinroles { get; set; }
        public virtual DbSet<mysql_membership> mysql_membership { get; set; }
        public virtual DbSet<orderanalysisdetailtbl> orderanalysisdetailtbls { get; set; }
        public virtual DbSet<ordermastertbl> ordermastertbls { get; set; }
        public virtual DbSet<ordernavigationtbl> ordernavigationtbls { get; set; }
        public virtual DbSet<orderpricedetailtbl> orderpricedetailtbls { get; set; }
        public virtual DbSet<ordersampletbl> ordersampletbls { get; set; }
        public virtual DbSet<packagedetailtbl> packagedetailtbls { get; set; }
        public virtual DbSet<packagetbl> packagetbls { get; set; }
        public virtual DbSet<parameterstbl> parameterstbls { get; set; }
        public virtual DbSet<paymenttbl> paymenttbls { get; set; }
        public virtual DbSet<resulttbl> resulttbls { get; set; }
        public virtual DbSet<reviewingtbl> reviewingtbls { get; set; }
        public virtual DbSet<roletbl> roletbls { get; set; }
        public virtual DbSet<standarddetailtbl> standarddetailtbls { get; set; }
        public virtual DbSet<standardtbl> standardtbls { get; set; }
        public virtual DbSet<workflowlogtbl> workflowlogtbls { get; set; }
        public virtual DbSet<sampletypetbl> sampletypetbls { get; set; }
    }
}
