//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BalitTanahPelayanan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class standarddetailtbl
    {
        public int stdDetailId { get; set; }
        public int stdId { get; set; }
        public int elementId { get; set; }
        public string creaBy { get; set; }
        public Nullable<System.DateTime> creaDate { get; set; }
        public string modBy { get; set; }
        public Nullable<System.DateTime> modDate { get; set; }
    
        public virtual elementservicestbl elementservicestbl { get; set; }
        public virtual standardtbl standardtbl { get; set; }
    }
}
