//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.app {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.app.language", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to received sample.
        /// </summary>
        internal static string accepted_sample {
            get {
                return ResourceManager.GetString("accepted_sample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Name.
        /// </summary>
        internal static string account_name {
            get {
                return ResourceManager.GetString("account_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the account owner name .
        /// </summary>
        internal static string account_name_desc {
            get {
                return ResourceManager.GetString("account_name_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account No.
        /// </summary>
        internal static string account_no {
            get {
                return ResourceManager.GetString("account_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the account bank no.
        /// </summary>
        internal static string account_no_desc {
            get {
                return ResourceManager.GetString("account_no_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to actions.
        /// </summary>
        internal static string actions {
            get {
                return ResourceManager.GetString("actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a New Order.
        /// </summary>
        internal static string add_new_order {
            get {
                return ResourceManager.GetString("add_new_order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to agency : .
        /// </summary>
        internal static string agency {
            get {
                return ResourceManager.GetString("agency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to agree.
        /// </summary>
        internal static string agree {
            get {
                return ResourceManager.GetString("agree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to analisys type : .
        /// </summary>
        internal static string analisystype {
            get {
                return ResourceManager.GetString("analisystype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to analysis type.
        /// </summary>
        internal static string analysis_type {
            get {
                return ResourceManager.GetString("analysis_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to approve.
        /// </summary>
        internal static string approve {
            get {
                return ResourceManager.GetString("approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to approval order.
        /// </summary>
        internal static string appr_order {
            get {
                return ResourceManager.GetString("appr_order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to attachment.
        /// </summary>
        internal static string attachment {
            get {
                return ResourceManager.GetString("attachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to back.
        /// </summary>
        internal static string back {
            get {
                return ResourceManager.GetString("back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no balittanah.
        /// </summary>
        internal static string balittanah_no {
            get {
                return ResourceManager.GetString("balittanah_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to balittanah number.
        /// </summary>
        internal static string balittanah_number {
            get {
                return ResourceManager.GetString("balittanah_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Name.
        /// </summary>
        internal static string bank_name {
            get {
                return ResourceManager.GetString("bank_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to batch.
        /// </summary>
        internal static string batch {
            get {
                return ResourceManager.GetString("batch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch No (Auto Generate).
        /// </summary>
        internal static string batchauto {
            get {
                return ResourceManager.GetString("batchauto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch Detail.
        /// </summary>
        internal static string batchdetail {
            get {
                return ResourceManager.GetString("batchdetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch Order.
        /// </summary>
        internal static string batchorder {
            get {
                return ResourceManager.GetString("batchorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch ID.
        /// </summary>
        internal static string batch_ID {
            get {
                return ResourceManager.GetString("batch_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to batch list.
        /// </summary>
        internal static string batch_list {
            get {
                return ResourceManager.GetString("batch_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch No.
        /// </summary>
        internal static string batch_no {
            get {
                return ResourceManager.GetString("batch_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to task board.
        /// </summary>
        internal static string Board {
            get {
                return ResourceManager.GetString("Board", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to re-analysis.
        /// </summary>
        internal static string btn_analisa_ulang {
            get {
                return ResourceManager.GetString("btn_analisa_ulang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to back.
        /// </summary>
        internal static string btn_kembali {
            get {
                return ResourceManager.GetString("btn_kembali", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve.
        /// </summary>
        internal static string Btn_setuju {
            get {
                return ResourceManager.GetString("Btn_setuju", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save.
        /// </summary>
        internal static string btn_simpan {
            get {
                return ResourceManager.GetString("btn_simpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to change.
        /// </summary>
        internal static string btn_ubah {
            get {
                return ResourceManager.GetString("btn_ubah", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to change.
        /// </summary>
        internal static string change {
            get {
                return ResourceManager.GetString("change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to choose commodity.
        /// </summary>
        internal static string choice_comodity {
            get {
                return ResourceManager.GetString("choice_comodity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to choose.
        /// </summary>
        internal static string choose {
            get {
                return ResourceManager.GetString("choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose commodity..
        /// </summary>
        internal static string choose_a_comodity {
            get {
                return ResourceManager.GetString("choose_a_comodity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to choose penyelia.
        /// </summary>
        internal static string choose_pic {
            get {
                return ResourceManager.GetString("choose_pic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select province..
        /// </summary>
        internal static string choose_province {
            get {
                return ResourceManager.GetString("choose_province", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose type of analysis..
        /// </summary>
        internal static string choose_type_analysis {
            get {
                return ResourceManager.GetString("choose_type_analysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose type of soil..
        /// </summary>
        internal static string choose_type_soil {
            get {
                return ResourceManager.GetString("choose_type_soil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to close.
        /// </summary>
        internal static string close {
            get {
                return ResourceManager.GetString("close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to comodity.
        /// </summary>
        internal static string commodity {
            get {
                return ResourceManager.GetString("commodity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to commodity : .
        /// </summary>
        internal static string commodity1 {
            get {
                return ResourceManager.GetString("commodity1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm New Order.
        /// </summary>
        internal static string ConfirmNewOrder {
            get {
                return ResourceManager.GetString("ConfirmNewOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cost.
        /// </summary>
        internal static string cost {
            get {
                return ResourceManager.GetString("cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to count number.
        /// </summary>
        internal static string count_number {
            get {
                return ResourceManager.GetString("count_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Batch.
        /// </summary>
        internal static string createbatch {
            get {
                return ResourceManager.GetString("createbatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        internal static string customer {
            get {
                return ResourceManager.GetString("customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Info.
        /// </summary>
        internal static string customer_info {
            get {
                return ResourceManager.GetString("customer_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to customer name.
        /// </summary>
        internal static string customer_name {
            get {
                return ResourceManager.GetString("customer_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer name : .
        /// </summary>
        internal static string cust_name {
            get {
                return ResourceManager.GetString("cust_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sample list.
        /// </summary>
        internal static string daftar_sampel {
            get {
                return ResourceManager.GetString("daftar_sampel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to date :.
        /// </summary>
        internal static string date {
            get {
                return ResourceManager.GetString("date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Received.
        /// </summary>
        internal static string date_received {
            get {
                return ResourceManager.GetString("date_received", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete.
        /// </summary>
        internal static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample description.
        /// </summary>
        internal static string desc_sample {
            get {
                return ResourceManager.GetString("desc_sample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to detail.
        /// </summary>
        internal static string detail {
            get {
                return ResourceManager.GetString("detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to detail order no.
        /// </summary>
        internal static string detail_order_no {
            get {
                return ResourceManager.GetString("detail_order_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to district.
        /// </summary>
        internal static string district {
            get {
                return ResourceManager.GetString("district", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to download.
        /// </summary>
        internal static string downl {
            get {
                return ResourceManager.GetString("downl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to download batch.
        /// </summary>
        internal static string download_batch {
            get {
                return ResourceManager.GetString("download_batch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to download result (LHP).
        /// </summary>
        internal static string download_lhp {
            get {
                return ResourceManager.GetString("download_lhp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to download template.
        /// </summary>
        internal static string download_template {
            get {
                return ResourceManager.GetString("download_template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to duplicate.
        /// </summary>
        internal static string duplicate {
            get {
                return ResourceManager.GetString("duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to download excel measurement results.
        /// </summary>
        internal static string dwnloadexcelpengukuran {
            get {
                return ResourceManager.GetString("dwnloadexcelpengukuran", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to download CSV files from tools.
        /// </summary>
        internal static string dwnloadfilecsv {
            get {
                return ResourceManager.GetString("dwnloadfilecsv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to parameter test list.
        /// </summary>
        internal static string element_code {
            get {
                return ResourceManager.GetString("element_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty Data.
        /// </summary>
        internal static string empty_data {
            get {
                return ResourceManager.GetString("empty_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to evaluation of results.
        /// </summary>
        internal static string evaluation_of_results {
            get {
                return ResourceManager.GetString("evaluation_of_results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to additional cost.
        /// </summary>
        internal static string extra_cost {
            get {
                return ResourceManager.GetString("extra_cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill details about the sample..
        /// </summary>
        internal static string fill_detail_sample {
            get {
                return ResourceManager.GetString("fill_detail_sample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill latitude and longitude..
        /// </summary>
        internal static string fill_latitude_longitude {
            get {
                return ResourceManager.GetString("fill_latitude_longitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill sampling date..
        /// </summary>
        internal static string fill_sampling_date {
            get {
                return ResourceManager.GetString("fill_sampling_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to close order.
        /// </summary>
        internal static string finish_order {
            get {
                return ResourceManager.GetString("finish_order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to genus total.
        /// </summary>
        internal static string genus_total {
            get {
                return ResourceManager.GetString("genus_total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gps.
        /// </summary>
        internal static string gps {
            get {
                return ResourceManager.GetString("gps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gps coordinates.
        /// </summary>
        internal static string gps_coordinates {
            get {
                return ResourceManager.GetString("gps_coordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost of Heavy Metal Test per Sample (Rp.).
        /// </summary>
        internal static string harga_logam {
            get {
                return ResourceManager.GetString("harga_logam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I agree to continue this order in accordance with standard procedures applicable at Balitanah.
        /// </summary>
        internal static string iagree {
            get {
                return ResourceManager.GetString("iagree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sample is accepted.
        /// </summary>
        internal static string is_received {
            get {
                return ResourceManager.GetString("is_received", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lab.
        /// </summary>
        internal static string lab {
            get {
                return ResourceManager.GetString("lab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to landuse.
        /// </summary>
        internal static string landuse {
            get {
                return ResourceManager.GetString("landuse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to soil type.
        /// </summary>
        internal static string land_use {
            get {
                return ResourceManager.GetString("land_use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LHP Result.
        /// </summary>
        internal static string lhpresult {
            get {
                return ResourceManager.GetString("lhpresult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of Test Parameters.
        /// </summary>
        internal static string List_of_Test_Parameters {
            get {
                return ResourceManager.GetString("List_of_Test_Parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to analysis type:.
        /// </summary>
        internal static string Lit_Analisis {
            get {
                return ResourceManager.GetString("Lit_Analisis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to customer name:.
        /// </summary>
        internal static string Lit_Customer {
            get {
                return ResourceManager.GetString("Lit_Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to village:.
        /// </summary>
        internal static string Lit_Desa {
            get {
                return ResourceManager.GetString("Lit_Desa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPS:.
        /// </summary>
        internal static string Lit_GPS {
            get {
                return ResourceManager.GetString("Lit_GPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to district : .
        /// </summary>
        internal static string Lit_Kabupaten {
            get {
                return ResourceManager.GetString("Lit_Kabupaten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sub district : .
        /// </summary>
        internal static string Lit_Kecamatan {
            get {
                return ResourceManager.GetString("Lit_Kecamatan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to comodity : .
        /// </summary>
        internal static string Lit_Komoditas {
            get {
                return ResourceManager.GetString("Lit_Komoditas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to balittanah number : .
        /// </summary>
        internal static string Lit_NoBalittanah {
            get {
                return ResourceManager.GetString("Lit_NoBalittanah", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to detail order number : .
        /// </summary>
        internal static string Lit_NoOrder {
            get {
                return ResourceManager.GetString("Lit_NoOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sample number : .
        /// </summary>
        internal static string Lit_NoSampel {
            get {
                return ResourceManager.GetString("Lit_NoSampel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to price total : .
        /// </summary>
        internal static string Lit_Price {
            get {
                return ResourceManager.GetString("Lit_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to province : .
        /// </summary>
        internal static string Lit_Propinsi {
            get {
                return ResourceManager.GetString("Lit_Propinsi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sample total : .
        /// </summary>
        internal static string Lit_Sampel {
            get {
                return ResourceManager.GetString("Lit_Sampel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status :.
        /// </summary>
        internal static string Lit_status {
            get {
                return ResourceManager.GetString("Lit_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to landuse : .
        /// </summary>
        internal static string Lit_Tanah {
            get {
                return ResourceManager.GetString("Lit_Tanah", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to logout.
        /// </summary>
        internal static string logout {
            get {
                return ResourceManager.GetString("logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heavy Metal Test.
        /// </summary>
        internal static string metal_test {
            get {
                return ResourceManager.GetString("metal_test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to customer name : .
        /// </summary>
        internal static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name.
        /// </summary>
        internal static string namee {
            get {
                return ResourceManager.GetString("namee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Batch.
        /// </summary>
        internal static string new_batch {
            get {
                return ResourceManager.GetString("new_batch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to balittanah no.
        /// </summary>
        internal static string no_balittanah {
            get {
                return ResourceManager.GetString("no_balittanah", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No. Sample Balit Tanah.
        /// </summary>
        internal static string no_sampel_balit_tanah {
            get {
                return ResourceManager.GetString("no_sampel_balit_tanah", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No. sample customer.
        /// </summary>
        internal static string no_sample_customer {
            get {
                return ResourceManager.GetString("no_sample_customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to order.
        /// </summary>
        internal static string order {
            get {
                return ResourceManager.GetString("order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to order complete.
        /// </summary>
        internal static string order_complete {
            get {
                return ResourceManager.GetString("order_complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order date..
        /// </summary>
        internal static string order_date {
            get {
                return ResourceManager.GetString("order_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to order entry.
        /// </summary>
        internal static string order_entry {
            get {
                return ResourceManager.GetString("order_entry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to order information.
        /// </summary>
        internal static string order_info {
            get {
                return ResourceManager.GetString("order_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to order list.
        /// </summary>
        internal static string order_list {
            get {
                return ResourceManager.GetString("order_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new order.
        /// </summary>
        internal static string order_new {
            get {
                return ResourceManager.GetString("order_new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to order no.
        /// </summary>
        internal static string order_no {
            get {
                return ResourceManager.GetString("order_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to order processed.
        /// </summary>
        internal static string order_processed {
            get {
                return ResourceManager.GetString("order_processed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to order statistics.
        /// </summary>
        internal static string order_statistik {
            get {
                return ResourceManager.GetString("order_statistik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to order status.
        /// </summary>
        internal static string order_status {
            get {
                return ResourceManager.GetString("order_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to order no : .
        /// </summary>
        internal static string ord_no {
            get {
                return ResourceManager.GetString("ord_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to parameter test.
        /// </summary>
        internal static string parameter_test {
            get {
                return ResourceManager.GetString("parameter_test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Receipt.
        /// </summary>
        internal static string payment_receipt {
            get {
                return ResourceManager.GetString("payment_receipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to payment status.
        /// </summary>
        internal static string payment_status {
            get {
                return ResourceManager.GetString("payment_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to payment type.
        /// </summary>
        internal static string payment_type {
            get {
                return ResourceManager.GetString("payment_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay via Transfer.
        /// </summary>
        internal static string pay_transfer {
            get {
                return ResourceManager.GetString("pay_transfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIC.
        /// </summary>
        internal static string pic {
            get {
                return ResourceManager.GetString("pic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to penyelia name.
        /// </summary>
        internal static string picname {
            get {
                return ResourceManager.GetString("picname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIC Analyst.
        /// </summary>
        internal static string PIC_Analis {
            get {
                return ResourceManager.GetString("PIC_Analis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select parameter.
        /// </summary>
        internal static string pilihparameteruji {
            get {
                return ResourceManager.GetString("pilihparameteruji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to price total : .
        /// </summary>
        internal static string pricetot {
            get {
                return ResourceManager.GetString("pricetot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to price per genus.
        /// </summary>
        internal static string price_per_genus {
            get {
                return ResourceManager.GetString("price_per_genus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to price total.
        /// </summary>
        internal static string price_total {
            get {
                return ResourceManager.GetString("price_total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to print receipt.
        /// </summary>
        internal static string print {
            get {
                return ResourceManager.GetString("print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to print qr.
        /// </summary>
        internal static string printQR {
            get {
                return ResourceManager.GetString("printQR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to print barcode.
        /// </summary>
        internal static string print_barcode {
            get {
                return ResourceManager.GetString("print_barcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to print request form.
        /// </summary>
        internal static string print_request {
            get {
                return ResourceManager.GetString("print_request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to print total.
        /// </summary>
        internal static string print_total {
            get {
                return ResourceManager.GetString("print_total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to preview.
        /// </summary>
        internal static string print_view {
            get {
                return ResourceManager.GetString("print_view", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to process.
        /// </summary>
        internal static string process {
            get {
                return ResourceManager.GetString("process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to process lab.
        /// </summary>
        internal static string process_lab {
            get {
                return ResourceManager.GetString("process_lab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to progress.
        /// </summary>
        internal static string progress {
            get {
                return ResourceManager.GetString("progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to province.
        /// </summary>
        internal static string province {
            get {
                return ResourceManager.GetString("province", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rates per example.
        /// </summary>
        internal static string rates_per_example {
            get {
                return ResourceManager.GetString("rates_per_example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recalculate.
        /// </summary>
        internal static string recalculate {
            get {
                return ResourceManager.GetString("recalculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reject.
        /// </summary>
        internal static string reject {
            get {
                return ResourceManager.GetString("reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to remark.
        /// </summary>
        internal static string remark {
            get {
                return ResourceManager.GetString("remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to result.
        /// </summary>
        internal static string result {
            get {
                return ResourceManager.GetString("result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to result (LHP).
        /// </summary>
        internal static string result_lhp {
            get {
                return ResourceManager.GetString("result_lhp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reviewing.
        /// </summary>
        internal static string reviewing {
            get {
                return ResourceManager.GetString("reviewing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sample list.
        /// </summary>
        internal static string samplelist {
            get {
                return ResourceManager.GetString("samplelist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sample total : .
        /// </summary>
        internal static string sampletot {
            get {
                return ResourceManager.GetString("sampletot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sample code.
        /// </summary>
        internal static string sample_code {
            get {
                return ResourceManager.GetString("sample_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sample info.
        /// </summary>
        internal static string sample_info {
            get {
                return ResourceManager.GetString("sample_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sample is accepted.
        /// </summary>
        internal static string sample_is_accepted {
            get {
                return ResourceManager.GetString("sample_is_accepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sample list.
        /// </summary>
        internal static string sample_list {
            get {
                return ResourceManager.GetString("sample_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sample name.
        /// </summary>
        internal static string sample_name {
            get {
                return ResourceManager.GetString("sample_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new sample.
        /// </summary>
        internal static string sample_new {
            get {
                return ResourceManager.GetString("sample_new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sample no.
        /// </summary>
        internal static string sample_no {
            get {
                return ResourceManager.GetString("sample_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sample number.
        /// </summary>
        internal static string sample_number {
            get {
                return ResourceManager.GetString("sample_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sample type.
        /// </summary>
        internal static string sample_type {
            get {
                return ResourceManager.GetString("sample_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sampling date.
        /// </summary>
        internal static string sampling_date {
            get {
                return ResourceManager.GetString("sampling_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save.
        /// </summary>
        internal static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select PIC.
        /// </summary>
        internal static string selectPIC {
            get {
                return ResourceManager.GetString("selectPIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select sub commodity..
        /// </summary>
        internal static string select_sub_comodity {
            get {
                return ResourceManager.GetString("select_sub_comodity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to send notification.
        /// </summary>
        internal static string send_notif {
            get {
                return ResourceManager.GetString("send_notif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to serial no.
        /// </summary>
        internal static string serial_no {
            get {
                return ResourceManager.GetString("serial_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to standard procedure.
        /// </summary>
        internal static string sop {
            get {
                return ResourceManager.GetString("sop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string status {
            get {
                return ResourceManager.GetString("status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to payment type.
        /// </summary>
        internal static string status_type {
            get {
                return ResourceManager.GetString("status_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sub commodity : .
        /// </summary>
        internal static string subcommodity {
            get {
                return ResourceManager.GetString("subcommodity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sub commodity.
        /// </summary>
        internal static string sub_commodity {
            get {
                return ResourceManager.GetString("sub_commodity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sub commodity :.
        /// </summary>
        internal static string sub_commodity1 {
            get {
                return ResourceManager.GetString("sub_commodity1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sub district.
        /// </summary>
        internal static string sub_district {
            get {
                return ResourceManager.GetString("sub_district", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supervisor.
        /// </summary>
        internal static string supervisor {
            get {
                return ResourceManager.GetString("supervisor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to status.
        /// </summary>
        internal static string testing_status {
            get {
                return ResourceManager.GetString("testing_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to test parameter.
        /// </summary>
        internal static string test_parameter {
            get {
                return ResourceManager.GetString("test_parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Verification.
        /// </summary>
        internal static string title_payment_verification {
            get {
                return ResourceManager.GetString("title_payment_verification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to order processed.
        /// </summary>
        internal static string title_pesanan_diproses {
            get {
                return ResourceManager.GetString("title_pesanan_diproses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to order entry.
        /// </summary>
        internal static string title_pesanan_masuk {
            get {
                return ResourceManager.GetString("title_pesanan_masuk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to order complete.
        /// </summary>
        internal static string title_pesanan_selesai {
            get {
                return ResourceManager.GetString("title_pesanan_selesai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Cost.
        /// </summary>
        internal static string title_tambahan {
            get {
                return ResourceManager.GetString("title_tambahan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Additional Cost (Total Samples x Genus x Price per Genus).
        /// </summary>
        internal static string total_add_genus {
            get {
                return ResourceManager.GetString("total_add_genus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Cost : Rp..
        /// </summary>
        internal static string total_biaya {
            get {
                return ResourceManager.GetString("total_biaya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to total example.
        /// </summary>
        internal static string total_example {
            get {
                return ResourceManager.GetString("total_example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to total order.
        /// </summary>
        internal static string total_order {
            get {
                return ResourceManager.GetString("total_order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to total order complete.
        /// </summary>
        internal static string total_order_complete {
            get {
                return ResourceManager.GetString("total_order_complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to total order entry.
        /// </summary>
        internal static string total_order_entry {
            get {
                return ResourceManager.GetString("total_order_entry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to total order processed.
        /// </summary>
        internal static string total_order_processed {
            get {
                return ResourceManager.GetString("total_order_processed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Test Parameters : .
        /// </summary>
        internal static string total_parameter_uji {
            get {
                return ResourceManager.GetString("total_parameter_uji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to total price.
        /// </summary>
        internal static string total_price {
            get {
                return ResourceManager.GetString("total_price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to total sample.
        /// </summary>
        internal static string total_sample {
            get {
                return ResourceManager.GetString("total_sample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Additional Cost (Number of Samples x Cost of Heavy Metal Test per Sample).
        /// </summary>
        internal static string total_tambahan {
            get {
                return ResourceManager.GetString("total_tambahan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Transfer.
        /// </summary>
        internal static string total_transfer {
            get {
                return ResourceManager.GetString("total_transfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to total transferred amount .
        /// </summary>
        internal static string total_transfer_desc {
            get {
                return ResourceManager.GetString("total_transfer_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to analysis type.
        /// </summary>
        internal static string type_analyst {
            get {
                return ResourceManager.GetString("type_analyst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select district..
        /// </summary>
        internal static string type_name_district {
            get {
                return ResourceManager.GetString("type_name_district", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select sub-district..
        /// </summary>
        internal static string type_name_subdistrict {
            get {
                return ResourceManager.GetString("type_name_subdistrict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select village..
        /// </summary>
        internal static string type_name_vilage {
            get {
                return ResourceManager.GetString("type_name_vilage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to upload.
        /// </summary>
        internal static string upload {
            get {
                return ResourceManager.GetString("upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to upload excel measurement results.
        /// </summary>
        internal static string uploadexcel {
            get {
                return ResourceManager.GetString("uploadexcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to upload CSV files from tools.
        /// </summary>
        internal static string uploadfiledarialat {
            get {
                return ResourceManager.GetString("uploadfiledarialat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to upload result (LHP).
        /// </summary>
        internal static string upload_lhp {
            get {
                return ResourceManager.GetString("upload_lhp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to view.
        /// </summary>
        internal static string view {
            get {
                return ResourceManager.GetString("view", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to village.
        /// </summary>
        internal static string village {
            get {
                return ResourceManager.GetString("village", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to welcome.
        /// </summary>
        internal static string welcome {
            get {
                return ResourceManager.GetString("welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zoom the text.
        /// </summary>
        internal static string zoom {
            get {
                return ResourceManager.GetString("zoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to continue.
        /// </summary>
        internal static string _continue {
            get {
                return ResourceManager.GetString("continue", resourceCulture);
            }
        }
    }
}
